<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<EnableDefaultContentItems>false</EnableDefaultContentItems>
	<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

	<PropertyGroup>
		<BuiltByCI Condition="'$(BuiltByCI)' == ''">NO</BuiltByCI>
		<BuildDate Condition="'$(BuildDate)' == ''">development</BuildDate>
		<CommitHash Condition="'$(CommitHash)' == ''">development</CommitHash>
		<PipelineId Condition="'$(PipelineId)' == ''">development</PipelineId>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>BuiltByCI</_Parameter1>
			<_Parameter2>$(BuiltByCI)</_Parameter2>
		</AssemblyAttribute>

		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>BuildDate</_Parameter1>
			<_Parameter2>$(BuildDate)</_Parameter2>
		</AssemblyAttribute>

		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>CommitHash</_Parameter1>
			<_Parameter2>$(CommitHash)</_Parameter2>
		</AssemblyAttribute>

		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>PipelineId</_Parameter1>
			<_Parameter2>$(PipelineId)</_Parameter2>
		</AssemblyAttribute>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="7.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.1" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="3.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dal\Entities\" />
  </ItemGroup>

</Project>
